### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by TheAdminDavid** [hangy/azure-boards-estimate#73]
Hello,

Since we are Evaluating to use this Estimation Tool in our AzureDev Ops Instance, we would like to know if there is some kind of Privacy Policy which describes what Data you collect when using this Extension?

Thanks for the feedback.
Best Regards
David

**Comment by hangy** [comment]
Hi David,

I don't have a privacy policy, because that's not my specialty. The access_log in nginx (reverse proxy for the [backend](https://github.com/hangy/azure-boards-estimate-backend)) is disabled, and the session data is kept in-memory by [SignalR](https://github.com/hangy/azure-boards-estimate-backend/blob/5851944184de5ae68fdcc3140bac3e763518abad/azure-boards-estimate-backend/Hubs/EstimateHub.cs). I know that this might not be sufficient for some companies that require a GDPR compliant policy, so I've been [working on a version](https://github.com/hangy/azure-boards-estimate/tree/backend-settings) that allows you to change the backend URL after the extension has been installed, so that you can host it yourself using [docker](https://github.com/hangy/azure-boards-estimate-backend/pkgs/container/azure-boards-estimate-backend). Would that be of interest to you?

Best,
hangy

**Comment by TheAdminDavid** [comment]
Hi Handy,

Thanks for the quick response.
That's understandable. Sadly you are right that this won't be sufficient for a bigger company.
But that new version of yours sounds interesting. Currently, we don't have the resources to manage a local backend, but I can see this in the future, and it's good to have such a possibility.

Best regards
David
